import { food } from './app/shared/models/food-model';
import { tags } from './app/shared/models/tags-model';
export const sample_foods: food[] = [
  {
    id: '1',
    name: 'Pizza',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: './assets/pizza.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '2',
    name: 'burger',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: './assets/burger.jpeg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id: '3',
    name: 'pasta',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: './assets/pasta.jpeg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id: '4',
    name: 'sushi',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: './assets/sushi.jpeg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id: '5',
    name: 'tacos',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: './assets/tacos.jpeg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id: '6',
    name: 'sushi roll',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: './assets/roll.jpeg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
];

export const sample_tags: tags[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];
